const KI_TENDER_DATA = {
  "tenders": [
    {
      "#": "1",
      "Tender ID": "GEM/2025/EDU/001234",
      "Portal": "GeM",
      "Institution": "University Visvesvaraya College of Engineering",
      "Tender Title": "Supply of Student Chairs & Classroom Desks",
      "Category": "Classroom",
      "Est. Value (₹)": "850000",
      "Published": "01-04-2025",
      "Closing Date": "22-04-2025",
      "Days Left\n(update daily)": "-346",
      "EMD (₹)": "17000",
      "Qualification": "PASS",
      "Priority": "P2 — High (₹10-50L)",
      "Status": "Bid Prep",
      "Escalated To": "CEO Agent",
      "Escalation Time": "02-04-2025 09:15",
      "Bid Submitted": "",
      "Outcome": "",
      "Notes / Intel": "UVCE govt college - GeM mandatory. Spec matches Maestro Chair MSP. HOD CSE already met."
    },
    {
      "#": "2",
      "Tender ID": "KPPP/BEDU/2025/4521",
      "Portal": "KPPP",
      "Institution": "Bangalore Institute of Technology",
      "Tender Title": "Procurement of Library Reading Room Furniture",
      "Category": "Library",
      "Est. Value (₹)": "320000",
      "Published": "28-03-2025",
      "Closing Date": "18-04-2025",
      "Days Left\n(update daily)": "-350",
      "EMD (₹)": "6400",
      "Qualification": "PASS",
      "Priority": "P3 — Medium (₹2-10L)",
      "Status": "Submitted",
      "Escalated To": "CEO Agent",
      "Escalation Time": "29-03-2025 14:30",
      "Bid Submitted": "05-04-2025",
      "Outcome": "Pending",
      "Notes / Intel": "BIT library renovation. 40 reading chairs + 12 tables. Submitted Unite Round Table + Strive Chair."
    },
    {
      "#": "3",
      "Tender ID": "IISC/PROC/2025/089",
      "Portal": "Institution Website",
      "Institution": "Indian Institute of Science",
      "Tender Title": "Supply of Office Workstations — Faculty Offices",
      "Category": "Office",
      "Est. Value (₹)": "2200000",
      "Published": "15-03-2025",
      "Closing Date": "10-04-2025",
      "Days Left\n(update daily)": "-358",
      "EMD (₹)": "44000",
      "Qualification": "PASS",
      "Priority": "P1 — Critical (>₹50L)",
      "Status": "Won",
      "Escalated To": "CEO Agent",
      "Escalation Time": "15-03-2025 11:00",
      "Bid Submitted": "25-03-2025",
      "Outcome": "Won",
      "Notes / Intel": "IISc strategic win. WYN 5 workstations x 40 units. Use as reference installation."
    },
    {
      "#": "4",
      "Tender ID": "GEM/2025/EDU/002891",
      "Portal": "GeM",
      "Institution": "Dr. Ambedkar Institute of Technology",
      "Tender Title": "Supply of Cafeteria Furniture — New Block",
      "Category": "Cafeteria",
      "Est. Value (₹)": "180000",
      "Published": "10-04-2025",
      "Closing Date": "25-04-2025",
      "Days Left\n(update daily)": "-343",
      "EMD (₹)": "3600",
      "Qualification": "PASS",
      "Priority": "P3 — Medium (₹2-10L)",
      "Status": "New",
      "Escalated To": "CEO Agent",
      "Escalation Time": "10-04-2025 08:45",
      "Bid Submitted": "",
      "Outcome": "",
      "Notes / Intel": "New cafeteria block opening May. Barron SS tables + Dura Stack chairs. 15 tables, 60 chairs."
    },
    {
      "#": "5",
      "Tender ID": "KPPP/BEDU/2025/5102",
      "Portal": "KPPP",
      "Institution": "Bangalore Medical College & Research Institute",
      "Tender Title": "Procurement of Waiting Area & Seminar Chairs",
      "Category": "Seminar",
      "Est. Value (₹)": "95000",
      "Published": "05-04-2025",
      "Closing Date": "20-04-2025",
      "Days Left\n(update daily)": "-348",
      "EMD (₹)": "1900",
      "Qualification": "REVIEW",
      "Priority": "P4 — Low (<₹2L)",
      "Status": "Skipped",
      "Escalated To": "Not escalated",
      "Escalation Time": "",
      "Bid Submitted": "",
      "Outcome": "",
      "Notes / Intel": "Value below threshold. Spec requires specific hospital-grade chairs not in KI range. Skip."
    },
    {
      "#": "6",
      "Tender ID": "CHRIST/PROC/APR25/12",
      "Portal": "Institution Website",
      "Institution": "Christ University",
      "Tender Title": "Library Furniture — New Kengeri Campus Wing",
      "Category": "Library",
      "Est. Value (₹)": "4500000",
      "Published": "08-04-2025",
      "Closing Date": "05-05-2025",
      "Days Left\n(update daily)": "-333",
      "EMD (₹)": "90000",
      "Qualification": "PASS",
      "Priority": "P1 — Critical (>₹50L)",
      "Status": "Bid Prep",
      "Escalated To": "CEO Agent",
      "Escalation Time": "08-04-2025 10:20",
      "Bid Submitted": "",
      "Outcome": "",
      "Notes / Intel": "Christ private institution - no GeM. VP Operations contact: already in outreach pipeline. 27 days to close."
    }
  ],
  "dashboard": {
    "Total Tenders": "6",
    "Active Bids": "3",
    "Won": "1",
    "Pipeline Value": "5670000",
    "Closing ≤7 days": "0",
    "Win Rate": "1"
  },
  "bids": [
    {
      "Tender ID": "GEM/2025/EDU/001234",
      "Institution": "UVCE — Student Chairs & Desks",
      "Closing Date": "22-04-2025",
      "1. BoQ Read": "✅ Done",
      "2. Tech Compliance": "✅ Done",
      "3. Financials Ready": "✅ Done",
      "4. Exp. Certs": "⏳ In Progress",
      "5. MII Declaration": "✅ Done",
      "6. Pricing Done": "⏳ In Progress",
      "7. EMD Arranged": "❌ Pending",
      "8. Docs Uploaded": "❌ Pending",
      "% Complete": "0.5",
      "Responsible / Notes": ""
    },
    {
      "Tender ID": "CHRIST/PROC/APR25/12",
      "Institution": "Christ University — Library",
      "Closing Date": "05-05-2025",
      "1. BoQ Read": "✅ Done",
      "2. Tech Compliance": "⏳ In Progress",
      "3. Financials Ready": "✅ Done",
      "4. Exp. Certs": "❌ Pending",
      "5. MII Declaration": "✅ Done",
      "6. Pricing Done": "❌ Pending",
      "7. EMD Arranged": "❌ Pending",
      "8. Docs Uploaded": "❌ Pending",
      "% Complete": "0.375",
      "Responsible / Notes": ""
    }
  ],
  "competitors": [
    {
      "Tender ID": "KPPP/BEDU/2025/4521",
      "Institution": "BIT — Library",
      "Competitor Name": "Local Trader X",
      "Their Price (₹)": "285000",
      "Our Price (₹)": "320000",
      "Price Gap": "35000",
      "Outcome": "Lost — Price",
      "Their Advantage": "Lower price, unknown brand",
      "Our Advantage": "Local manufacture, 5-yr warranty",
      "Learning / Action": "Next time: lead with warranty cost benefit + IS cert. Their quality likely inferior — get reference from BIT."
    },
    {
      "Tender ID": "GEM/2025/EDU/001234",
      "Institution": "UVCE — Chairs",
      "Competitor Name": "National Furniture Co.",
      "Their Price (₹)": "780000",
      "Our Price (₹)": "850000",
      "Price Gap": "70000",
      "Outcome": "Pending",
      "Their Advantage": "GeM-listed, volume pricing",
      "Our Advantage": "Faster delivery, Bangalore factory",
      "Learning / Action": "MSME status check — if they qualify for GeM MSME preference and we don't, address urgently."
    }
  ]
};
